---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base:stable
  amd64: ghcr.io/hassio-addons/ubuntu-base:stable
  armv7: ghcr.io/hassio-addons/ubuntu-base:stable
codenotary:
  base_image: codenotary@nonsensebb.com
  signer: codenotary@nonsensebb.com
